# Generated by Django 3.2.3 on 2021-06-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0002_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
